var PIDs={budget:{1:193,2:195,3:196,4:198,5:199,6:197,7:200,8:201,10:203,12:204,16:206,25:205},premium:{1:207,2:208,3:209,4:210,5:211,6:212,7:213,8:214,10:216,12:217,16:218,25:219}};function ucfirst(s){return s.charAt(0).toUpperCase()+s.slice(1)}
function get_plans(type){return Object.keys(PIDs[type]).map(k=>{var price=parseInt(k)*(type==="budget"?1:2.25);var minperiod=((type==="budget")&&(parseInt(k)<=3))?"quarterly":"monthly";price=(minperiod==='quarterly')?price*3:price;return{name:k+"GB "+ucfirst(type)+" Minecraft",price:price,ram:k+"GB",cycle:minperiod,ram_gb:parseInt(k),orderlink:"https://billing.pebblehost.com/cart.php?a=add&pid="+PIDs[type][k]}}).reduce(function(result,item,index,array){result[item.ram_gb]=item;return result;},{});}
var index=1;var type=$("input[name=hosting_type]").val();var info=get_plans(type);function setup_slider(main){var self=main,sliderUI=self.find('.slider-line'),sliderInp=self.find('.slider-inp'),sliderUniqueId='sliderUI'+index,inputUniqueId='inputUI'+index,start=parseInt(sliderInp.attr('data-start'));sliderUI.attr('id',sliderUniqueId);sliderInp.attr('id',inputUniqueId);index++;var count_step=Object.keys(info).length;var keypressSlider=document.getElementById(sliderUniqueId),input=document.getElementById(inputUniqueId);var slider=noUiSlider.create(keypressSlider,{start:start?start:1,step:1,connect:"lower",tooltips:true,format:{to:function(ind){var gb=info[Object.keys(info)[parseInt(ind)-1]].ram_gb;return parseInt(gb)+"GB "+ucfirst(type)+" Minecraft";},from:function(value){return value;}},range:{'min':1,'max':Object.keys(info).length},pips:{mode:'values',values:Object.keys(info).map((val,ind)=>ind+1),density:5,stepped:false,format:{to:function(a){return info[Object.keys(info)[parseInt(a)-1]].ram;}}}});function getValue2(values,handle,unencoded,tap){var circle=$(this.target).closest('.sidebar').find('.circle');circle.attr('data-percent',parseInt(unencoded)/count_step*100);}
keypressSlider.noUiSlider.on('change',getValue2);keypressSlider.noUiSlider.on('update',function(values,handle){refreshInfo(values[handle]);input.value=values[handle];change_global_cloud_pkgs_href(values[handle]);});input.addEventListener('change',function(){keypressSlider.noUiSlider.set([null,this.value]);});input.addEventListener('keydown',function(e){var value=Number(keypressSlider.noUiSlider.get()),sliderStep=keypressSlider.noUiSlider.steps()
sliderStep=sliderStep[0];switch(e.which){case 13:keypressSlider.noUiSlider.set(this.value);break;case 38:keypressSlider.noUiSlider.set(value+sliderStep[1]);break;case 40:keypressSlider.noUiSlider.set(value-sliderStep[0]);break;}});function refreshInfo(key){var gb=parseInt(key.split("GB")[0]);$("#orderlink-val").html(info[gb].orderlink);$("#price-val").html(info[gb].price.toFixed(2));$("#cycle-val").html('/'+info[gb].cycle.substr(0,info[gb].cycle.length-2));$("#plan-name").html(gb+"GB "+ucfirst(type)+" Minecraft")}
function change_global_cloud_pkgs_href(key){var gb=parseInt(key.split("GB")[0]);$("#orderlink").attr("href",info[gb].orderlink);}
return slider;}
var slider=setup_slider($("#plan-slider"))
var ver="1.13-plus";var jar="spigot";var recommendation=3;function calc_recommendation(){switch(jar){case 'spigot':case 'vanilla':return{"1.13-plus":3,"1.9-to-1.13":2,"1.8.8-below":1}[ver];case 'bedrock':return{"1.13-plus":2,"1.9-to-1.13":2,"1.8.8-below":2}[ver];case 'forge':return{"1.13-plus":6,"1.9-to-1.13":5,"1.8.8-below":4}[ver];}}
function update_recommendation(initial){recommendation=calc_recommendation();$("#chosen-version").text({"1.13-plus":"1.13.2 or above","1.9-to-1.13":"1.9 to 1.13.2","1.8.8-below":"1.8.8 or below"}[ver]);$("#chosen-jar").text({"spigot":"Spigot / Paper","vanilla":"Vanilla Minecraft","bedrock":"Bedrock","forge":"Forge Modpack",}[jar]);$("#chosen-ram").text(recommendation+"GB");if(initial)recommendation=5;var i=1;for(var key in info){if(parseInt(key)===parseInt(recommendation)){slider.set(i);}
i++;}}
$("#choose-version").change(function(){ver=$(this).find("option:selected").val();update_recommendation();})
$("#choose-jar").change(function(){jar=$(this).find("option:selected").val();update_recommendation();})
update_recommendation(true);